language: elixir

elixir:
  - 1.6.6
  - 1.7.4
  - 1.8.2
  - 1.9.2

otp_release:
  - 20.3
  - 21.3
  - 22.1

matrix:
  include:
    - elixir: 1.6.6
      otp_release: 19.3
  exclude:
    - elixir: 1.6.6
      otp_release: 22.1

before_script:
  - mix do deps.get, deps.compile
  - MIX_ENV=test mix compile --warnings-as-errors
  - travis_wait mix dialyzer --plt

script:
  - if [[ "$TRAVIS_ELIXIR_VERSION" == "1.9"* ]]; then mix format --check-formatted ;fi
  - mix credo --strict
  - mix test
  - mix dialyzer --halt-exit-status

sudo: required

dist: trusty

cache:
  directories:
    - deps
    - test/support/plts

